### ISSUE TITLE
Final Group Capstone Kanban Board

### ISSUE THREAD

**Issue by demix007** [demix007/car-rentals-backend#18]
![Hello](https://media.giphy.com/media/26xBwdIuRJiAIqHwA/giphy.gif)

Below is a link to our final group capstone Kanban Board, our team consists of four(4) individuals namely:

- @demix007 
- @houdamzari 
- @MohamedHNoor 
- @Kashif-Saleem-Ghuman 

## Kanban Board Screenshot:

![Screenshot (95)](https://user-images.githubusercontent.com/35904766/236182661-84c29b84-b7c0-42c3-aa74-489a8f94812b.png)

**Comment by Meltrust** [comment]
Hi today,


## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal according to the requirements✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
